# Generated by Django 6.1 on 2026-09-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
